apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotmesh-docs
  namespace: docs
  annotations:
    keel.sh/policy: force
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: dotmesh-docs
        image: quay.io/dotmesh/docs:latest 
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5